### ISSUE TITLE
Bug: spring-boot:run not working

### ISSUE THREAD

**Issue by patrick-werner** [hapifhir/hapi-fhir-jpaserver-starter#157]
I just tried to start the current version with: 
`mvn spring-boot:run -Dspring-boot.run.profiles=boot ` without success. It is missing the ServletWebServerFactory bean.

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-10-25 14:24:35.792 [main] ERROR o.s.boot.SpringApplication [SpringApplication.java:837] Application run failed
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at ca.uhn.fhir.jpa.starter.Application.main(Application.java:31)
Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:205)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:177)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:158)
        ... 9 common frames omitted
[INFO] ---------------------------------
```

**Comment by jvitrifork** [comment]
doing mvn spring-boot:run -Pboot does the job

**Comment by jvitrifork** [comment]
the 'boot' is a compile-time maven profile - not a runtime profile as you specified it

**Comment by patrick-werner** [comment]
thanks for the explanation. I was brain dead during experimenting.

**Comment by jkiddo** [comment]
That happens to the best of us
