### ISSUE TITLE
Cannot load hl7.fhir.r3.core implementation guide

### ISSUE THREAD

**Issue by Milzor** [hapifhir/hapi-fhir-jpaserver-starter#170]
used configuration:

```
hapi:
  fhir:
    implementationguides:
      - url: https://packages.simplifier.net/hl7.fhir.r3.core/-/hl7.fhir.r3.core-3.0.2.tgz
        name: hl7.fhir.r3.core
        version: 3.0.2
```

The following error occurs during boot:

```
2020-11-18 17:07:39.566 [main] ERROR o.a.c.c.C.[Tomcat].[localhost].[/] [DirectJDKLog.java:175] Servlet.init() for servlet [jpaRestfulServer] threw exception
ca.uhn.fhir.parser.DataFormatException: Failed to parse JSON encoded FHIR content: Content does not appear to be FHIR JSON, first non-whitespace character was: '﻿' (must be '{')
	at ca.uhn.fhir.parser.json.jackson.JacksonStructure.load(JacksonStructure.java:118)
	at ca.uhn.fhir.parser.json.jackson.JacksonStructure.load(JacksonStructure.java:78)
	at ca.uhn.fhir.parser.JsonParser.doParseResource(JsonParser.java:195)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:750)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:798)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:808)
	at ca.uhn.fhir.jpa.packages.PackageInstallerSvcImpl.parseResourcesOfType(PackageInstallerSvcImpl.java:294)
	at ca.uhn.fhir.jpa.packages.PackageInstallerSvcImpl.install(PackageInstallerSvcImpl.java:200)
	at ca.uhn.fhir.jpa.packages.PackageInstallerSvcImpl.install(PackageInstallerSvcImpl.java:163)
	at ca.uhn.fhir.jpa.starter.BaseJpaRestfulServer.initialize(BaseJpaRestfulServer.java:354)
	at ca.uhn.fhir.jpa.starter.JpaRestfulServer.initialize(JpaRestfulServer.java:22)
	at ca.uhn.fhir.rest.server.RestfulServer.init(RestfulServer.java:1226)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:986)
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.load(TomcatEmbeddedContext.java:82)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2890)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.lambda$deferredLoadOnStartup$0(TomcatEmbeddedContext.java:65)
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.doWithThreadContextClassLoader(TomcatEmbeddedContext.java:106)
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.deferredLoadOnStartup(TomcatEmbeddedContext.java:64)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.performDeferredLoadOnStartup(TomcatWebServer.java:305)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:216)
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at ca.uhn.fhir.jpa.starter.Application.main(Application.java:31)
Caused by: ca.uhn.fhir.parser.DataFormatException: Content does not appear to be FHIR JSON, first non-whitespace character was: '﻿' (must be '{')
	at ca.uhn.fhir.parser.json.jackson.JacksonStructure.load(JacksonStructure.java:105)
	... 47 common frames omitted
```
Seems to be a BOM in at least the file `NamingSystem-4.3.1.json`.

**Comment by jvitrifork** [comment]
@Milzor - I can see that there are more NamingSystems that are with BOM. Another question is: Why would you like to load this IG, if its the core IG? The core valuesets and codesystems are already present in the HAPI FHIR code

**Comment by Milzor** [comment]
You're right. It's not needed when running DSTU3 profile.
