### ISSUE TITLE
Error when uploading terminology in HAPI FHIR R4 server using hapi-fhir-cli tool

### ISSUE THREAD

**Issue by azizul90** [hapifhir/hapi-fhir-jpaserver-starter#193]
I`m recently has successfully set up a FHIR server deployed using docker image (hapiproject/hapi:latest).  When I`m trying to upload LOINC terminology into the server, I`m encounter the following error **ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HTTP 400 : Unknown file: hapi-fhir-cli9140861092969243052.zip**.  

```
Below are complete log produced by hapi-fhir-cli tool.

[root@svr fhir-dataset]# ./hapi-fhir-cli upload-terminology -d loinc_2.69_PartFile_5.1.zip -d loinc_2.69_AnswerFile_2.69.zip -d loinc_2.69_MultiAxialHierarchy.zip -v r4 -t https://{domain-name}} -u http://loinc.org
------------------------------------------------------------
🔥  HAPI FHIR 5.2.0 - Command Line Tool
------------------------------------------------------------
Process ID                      : 30286@{server-hostname}
Max configured JVM memory (Xmx) : 6.9GB
Detected Java version           : 1.8.0_275
------------------------------------------------------------
2020-12-22 18:16:43.587 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: loinc_2.69_PartFile_5.1.zip
2020-12-22 18:16:43.812 [main] INFO  c.u.f.c.UploadTerminologyCommand File size is greater than 10 MB - Going to use a local file reference instead of a direct HTTP transfer. Note that this will only work when executing this command on the same server as the FHIR server itself.
2020-12-22 18:16:43.831 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: loinc_2.69_AnswerFile_2.69.zip
2020-12-22 18:16:43.844 [main] INFO  c.u.f.c.UploadTerminologyCommand Adding ZIP file: loinc_2.69_MultiAxialHierarchy.zip
2020-12-22 18:16:43.875 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2020-12-22 18:16:45.535 [main] ERROR c.u.f.c.UploadTerminologyCommand Received the following response:
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Unknown file: hapi-fhir-cli9140861092969243052.zip</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "Unknown file: hapi-fhir-cli9140861092969243052.zip"
  } ]
}
2020-12-22 18:16:45.537 [main] ERROR ca.uhn.fhir.cli.App Error during execution:
ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HTTP 400 : Unknown file: hapi-fhir-cli9140861092969243052.zip
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:302)
        at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
        at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:540)
        at ca.uhn.fhir.rest.client.impl.GenericClient$OperationInternal.execute(GenericClient.java:1314)
        at ca.uhn.fhir.cli.UploadTerminologyCommand.invokeOperation(UploadTerminologyCommand.java:204)
        at ca.uhn.fhir.cli.UploadTerminologyCommand.run(UploadTerminologyCommand.java:113)
        at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:268)
        at ca.uhn.fhir.cli.App.main(App.java:43)
2020-12-22 18:16:45.538 [Thread-0] INFO  ca.uhn.fhir.cli.App HAPI FHIR is shutting down...
```

**Comment by citizenrich** [comment]
I can reproduce this with SNOMED-CT on macOS with hapi-fhir-cli 5.2.0

**Comment by azizul90** [comment]
> 
> 
> I can reproduce this with SNOMED-CT on macOS with hapi-fhir-cli 5.2.0
> 
> Edit: Also confirmed with Ubuntu 20.04.

I haven`t test with SNOMED-CT but I able to upload terminology with LOINC version 2.68 but not for version 2.69.  Not sure if the current hapi-fhir-cli tool does not support latest version of LOINC.

**Comment by MacL3an** [comment]
I just ran into the same issue. Has anyone worked around it? Tried both LOINC and Snomed.

**Comment by MacL3an** [comment]
I just ran into the same issue. Has anyone worked around it? Tried both LOINC and Snomed. It seems to work fine starting the server using the CLI, but not when starting it using this project.

**Comment by joeflack4** [comment]
This issue is also mirrored here, where I provide much more detail, including the cause in my case, being _Docker issues_. More info: https://github.com/hapifhir/hapi-fhir/issues/3276

Another related issue: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/322

Related; this is also about LOINC, but a different error: https://github.com/hapifhir/hapi-fhir/issues/1629

**Comment by joeflack4** [comment]
Read down from here: https://github.com/hapifhir/hapi-fhir/issues/3276#issuecomment-1249965048
In this other thread, the problem is described as seeming to have to do with a fixed file size limit, and someone suggests how to override that limit to fix the issue.

So I guess the issue is fixable, but at the very least, there should be a better error message for when this happens.

**Comment by madduci** [comment]
I am trying to upload some terminology codes, but instead i receive another kind of error, asking for CSV files, which i don't have.

How can i overcome the need of CSV files?

```
2024-09-24 12:53:54.16 [main] INFO  c.u.f.c.UploadTerminologyCommand Compressed 690,2 kB bytes in 1 file(s) into 68 kB bytes
2024-09-24 12:53:54.17 [main] INFO  c.u.f.c.UploadTerminologyCommand Beginning upload - This may take a while...
2024-09-24 12:53:54.61 [main] ERROR c.u.f.c.UploadTerminologyCommand Received the following response:
{
  "resourceType": "OperationOutcome",
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "HAPI-0862: Could not find the following mandatory files in input: [AccessoryFiles/AnswerFile/AnswerList.csv, AccessoryFiles/AnswerFile/LoincAnswerListLink.csv, AccessoryFiles/DocumentOntology/DocumentOntology.csv, LoincTable/Loinc.csv, AccessoryFiles/MultiAxialHierarchy/MultiAxialHierarchy.csv, AccessoryFiles/LoincIeeeMedicalDeviceCodeMappingTable/LoincIeeeMedicalDeviceCodeMappingTable.csv, AccessoryFiles/ImagingDocuments/ImagingDocumentCodes.csv, AccessoryFiles/PartFile/Part.csv, AccessoryFiles/PartFile/PartRelatedCodeMapping.csv, AccessoryFiles/LoincRsnaRadiologyPlaybook/LoincRsnaRadiologyPlaybook.csv, AccessoryFiles/LoincUniversalLabOrdersValueSet/LoincUniversalLabOrdersValueSet.csv]"
  } ]
}
```

**Comment by cpeter0702** [comment]
I also encountered the same issue. When using the CLI to upload SNOMED codes, I received a similar error message. After investigating, I found that the ZIP file I obtained does not comply with the RF2 format. However, the SNOMED codes officially purchased in Taiwan are provided in CSV format. Is there any solution for handling CSV files? Thank you.

`D:\HapiFhir\hapi-fhir-7.2.3-cli>hapi-fhir-cli upload-terminology -d D:/HapiFhir/Terminology/健保署用的Snomed/SNOMED_20240801.zip -v r4 -t http://localhost:8080/fhir -u http://snomed.info/sct -s 10GB
------------------------------------------------------------
🔥 [1m HAPI FHIR[22m 7.2.3 - Command Line Tool
------------------------------------------------------------
Process ID                      : 9804@X300
Max configured JVM memory (Xmx) : 7.7GB
Detected Java version           : 17.0.12
------------------------------------------------------------
[32m2025-08-19[0;39m [1;32m10:10:51.31[0;39m [37m[main][0;39m [37mINFO [0;39m [1;34mc.u.f.c.LogbackUtil[0;39m [1;37mLogging configuration set from file /logback-cli-on.xml
[0;39mStandard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
[32m2025-08-19[0;39m [1;32m10:10:52.14[0;39m [37m[main][0;39m [37mINFO [0;39m [1;34mc.u.f.c.UploadTerminologyCommand[0;39m [1;37mReading D:\HapiFhir\Terminology\健保署用的Snomed\SNOMED_20240801.zip
[0;39m[32m2025-08-19[0;39m [1;32m10:10:52.15[0;39m [37m[main][0;39m [37mINFO [0;39m [1;34mc.u.f.c.UploadTerminologyCommand[0;39m [1;37mAdding ZIP file: D:/HapiFhir/Terminology/健保署用的Snomed/SNOMED_20240801.zip
[0;39m[32m2025-08-19[0;39m [1;32m10:10:53.80[0;39m [37m[main][0;39m [37mINFO [0;39m [1;34mc.u.f.c.UploadTerminologyCommand[0;39m [1;37mBeginning upload - This may take a while...
[0;39m[32m2025-08-19[0;39m [1;32m10:11:34.57[0;39m [37m[main][0;39m [37mERROR[0;39m [1;34mc.u.f.c.UploadTerminologyCommand[0;39m [1;37mReceived the following response:
{
  "resourceType": "OperationOutcome",
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "HAPI-0862: Could not find the following mandatory files in input: [Terminology/sct2_Description_Full, Terminology/sct2_Relationship_Full, Terminology/sct2_Concept_Full_]"
  } ]
}
[0;39m[32m2025-08-19[0;39m [1;32m10:11:34.57[0;39m [37m[main][0;39m [37mERROR[0;39m [1;34mca.uhn.fhir.cli.App[0;39m [1;37mError during execution:
[0;39mca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : HAPI-0862: Could not find the following mandatory files in input: [Terminology/sct2_Description_Full, Terminology/sct2_Relationship_Full, Terminology/sct2_Concept_Full_]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:317)
        at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:415)
        at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:585)
        at ca.uhn.fhir.rest.client.impl.GenericClient$OperationInternal.execute(GenericClient.java:1441)
        at ca.uhn.fhir.cli.UploadTerminologyCommand.invokeOperation(UploadTerminologyCommand.java:255)
        at ca.uhn.fhir.cli.UploadTerminologyCommand.run(UploadTerminologyCommand.java:151)
        at ca.uhn.fhir.cli.BaseApp.run(BaseApp.java:272)
        at ca.uhn.fhir.cli.App.main(App.java:42)
[32m2025-08-19[0;39m [1;32m10:11:34.57[0;39m [37m[Thread-0][0;39m [37mINFO [0;39m [1;34mca.uhn.fhir.cli.App[0;39m [1;37mHAPI FHIR is shutting down...
[0;39m`
