### ISSUE TITLE
Hapi server did not start with MsSql database

### ISSUE THREAD

**Issue by Koudysmen** [hapifhir/hapi-fhir-jpaserver-starter#203]
When I am trying start Hapi server using MsSql database I get the following error. The problem occure when hapi trying execute this sql command: 
```
SELECT TOP(@P0) RES_ID FROM ( SELECT t0.RES_ID FROM HFJ_RESOURCE t0 WHERE ((t0.RES_TYPE = @P1) AND (t0.RES_DELETED_AT IS NULL)) )  AS RES_ID
```

**In my assumption:** problem is with @P0 data type, because sql command expected that @P0 will be integer value but this value is string.

![image](https://user-images.githubusercontent.com/35274093/106601370-d979ce80-655b-11eb-939b-5ce307cc40bd.png)

Exception:
```
2021-02-02 10:27:58.069 [main] ERROR o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:142] The number of rows provided for a TOP or FETCH clauses row count parameter must be an integer.
2021-02-02 10:28:07.214 [main] ERROR c.u.f.j.s.b.sql.SearchQueryExecutor [SearchQueryExecutor.java:136] Failed to create or execute SQL query
org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:103)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2304)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2057)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2019)
	at org.hibernate.loader.Loader.scroll(Loader.java:2927)
	at org.hibernate.loader.custom.CustomLoader.scroll(CustomLoader.java:383)
	at org.hibernate.internal.SessionImpl.scrollCustomQuery(SessionImpl.java:2116)
	at org.hibernate.internal.AbstractSharedSessionContract.scroll(AbstractSharedSessionContract.java:1168)
	at org.hibernate.query.internal.NativeQueryImpl.doScroll(NativeQueryImpl.java:220)
	at org.hibernate.query.internal.AbstractProducedQuery.scroll(AbstractProducedQuery.java:1488)
	at org.hibernate.query.internal.AbstractProducedQuery.scroll(AbstractProducedQuery.java:111)
	at ca.uhn.fhir.jpa.search.builder.sql.SearchQueryExecutor.fetchNext(SearchQueryExecutor.java:122)
	at ca.uhn.fhir.jpa.search.builder.sql.SearchQueryExecutor.hasNext(SearchQueryExecutor.java:87)
	at ca.uhn.fhir.jpa.search.builder.SearchBuilder$QueryIterator.fetchNext(SearchBuilder.java:1076)
	at ca.uhn.fhir.jpa.search.builder.SearchBuilder$QueryIterator.hasNext(SearchBuilder.java:1207)
	at ca.uhn.fhir.jpa.search.SearchCoordinatorSvcImpl.lambda$executeQuery$4(SearchCoordinatorSvcImpl.java:501)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at ca.uhn.fhir.jpa.search.SearchCoordinatorSvcImpl.executeQuery(SearchCoordinatorSvcImpl.java:469)
	at ca.uhn.fhir.jpa.search.SearchCoordinatorSvcImpl.registerSearch(SearchCoordinatorSvcImpl.java:318)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy162.registerSearch(Unknown Source)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.search(BaseHapiFhirResourceDao.java:1298)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.search(BaseHapiFhirResourceDao.java:1240)
	at ca.uhn.fhir.jpa.dao.BaseHapiFhirResourceDao.search(BaseHapiFhirResourceDao.java:1234)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy236.search(Unknown Source)
	at ca.uhn.fhir.jpa.dao.DaoSearchParamProvider.search(DaoSearchParamProvider.java:42)
	at ca.uhn.fhir.jpa.searchparam.registry.SearchParamRegistryImpl.doRefresh(SearchParamRegistryImpl.java:271)
	at ca.uhn.fhir.jpa.dao.DaoSearchParamProvider.refreshCache(DaoSearchParamProvider.java:49)
	at ca.uhn.fhir.jpa.searchparam.registry.SearchParamRegistryImpl.lambda$refreshCacheWithRetry$5(SearchParamRegistryImpl.java:378)
	at ca.uhn.fhir.jpa.searchparam.retry.Retrier.lambda$runWithRetry$0(Retrier.java:90)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)
	at ca.uhn.fhir.jpa.searchparam.retry.Retrier.runWithRetry(Retrier.java:90)
	at ca.uhn.fhir.jpa.searchparam.registry.SearchParamRegistryImpl.refreshCacheWithRetry(SearchParamRegistryImpl.java:381)
	at ca.uhn.fhir.jpa.searchparam.registry.SearchParamRegistryImpl.requiresActiveSearchParams(SearchParamRegistryImpl.java:116)
	at ca.uhn.fhir.jpa.searchparam.registry.SearchParamRegistryImpl.getActiveSearchParam(SearchParamRegistryImpl.java:99)
	at ca.uhn.fhir.jpa.subscription.match.registry.SubscriptionLoader.doSyncSubscriptions(SubscriptionLoader.java:127)
	at ca.uhn.fhir.jpa.searchparam.retry.Retrier.lambda$runWithRetry$0(Retrier.java:90)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)
	at ca.uhn.fhir.jpa.searchparam.retry.Retrier.runWithRetry(Retrier.java:90)
	at ca.uhn.fhir.jpa.subscription.match.registry.SubscriptionLoader.doSyncSubscriptionsWithRetry(SubscriptionLoader.java:115)
	at ca.uhn.fhir.jpa.subscription.match.registry.SubscriptionLoader.syncSubscriptions(SubscriptionLoader.java:84)
	at ca.uhn.fhir.jpa.subscription.match.registry.SubscriptionLoader.scheduleJob(SubscriptionLoader.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at ca.uhn.fhir.jpa.starter.Application.main(Application.java:33)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The number of rows provided for a TOP or FETCH clauses row count parameter must be an integer.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:600)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:444)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
```

Add dependency for Mssql server

```
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>8.2.0.jre8</version>
</dependency>
```

My application yaml file:

```
    url: jdbc:sqlserver://localhost:1433;databaseName=Hapi;
    username: {userName}
    password: {password}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    max-active: 15
```

**Comment by Koudysmen** [comment]
This issue is not relevant for hapi-fhir-jpaserver-starter and i move it to the hapi-fhir.
