### ISSUE TITLE
Duplicate fragment name when running in Docker

### ISSUE THREAD

**Issue by Jammjammjamm** [hapifhir/hapi-fhir-jpaserver-starter#41]
I am able to run the server locally using `mvn jetty:run`, but I get the following error when trying to run the server in docker:
```
2019-07-29 17:18:28.232:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@5b275dab{hapi-fhir-jpaserver,/hapi-fhir-jpaserver,file:///tmp/jetty-0.0.0.0-8080-hapi-fhir-jpaserver.war-_hapi-fhir-jpaserver-any-823365860806749615.dir/webapp/,UNAVAILABLE}{/hapi-fhir-jpaserver.war}
java.lang.IllegalStateException: Duplicate fragment name: spring_web for
  jar:file:///tmp/jetty-0.0.0.0-8080-hapi-fhir-jpaserver.war-_hapi-fhir-jpaserver-any-823365860806749615.dir/webapp/WEB-INF/lib/spring-web-5.1.3.RELEASE.jar!/META-INF/web-fragment.xml and
  jar:file:///tmp/jetty-0.0.0.0-8080-hapi-fhir-jpaserver.war-_hapi-fhir-jpaserver-any-823365860806749615.dir/webapp/WEB-INF/lib/spring-web-5.1.6.RELEASE.jar!/META-INF/web-fragment.xml
```
At this point trying to access `http://localhost:8080/hapi-fhir-jpaserver/` gives a 503. Below is a complete log:
```
ᐅ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

ᐅ ./build-docker-image.sh
<snipped for brevity>
[INFO] BUILD SUCCESS
<snipped for brevity>
Successfully built 8d6e7a0f4a52
Successfully tagged hapi-fhir/hapi-fhir-jpaserver-starter:latest

ᐅ docker run -p 8080:8080 hapi-fhir/hapi-fhir-jpaserver-starter:latest
2019-07-29 17:25:58.836:INFO::main: Logging initialized @347ms to org.eclipse.jetty.util.log.StdErrLog
2019-07-29 17:25:59.266:INFO:oejs.Server:main: jetty-9.4.18.v20190429; built: 2019-04-29T20:42:08.989Z; git: e1bc35120a6617ee3df052294e433f3a25ce7097; jvm 1.8.0_212-b04
2019-07-29 17:25:59.302:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/] at interval 1
2019-07-29 17:26:01.307:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@5b275dab{hapi-fhir-jpaserver,/hapi-fhir-jpaserver,file:///tmp/jetty-0.0.0.0-8080-hapi-fhir-jpaserver.war-_hapi-fhir-jpaserver-any-960398556907507961.dir/webapp/,UNAVAILABLE}{/hapi-fhir-jpaserver.war}
java.lang.IllegalStateException: Duplicate fragment name: spring_web for jar:file:///tmp/jetty-0.0.0.0-8080-hapi-fhir-jpaserver.war-_hapi-fhir-jpaserver-any-960398556907507961.dir/webapp/WEB-INF/lib/spring-web-5.1.3.RELEASE.jar!/META-INF/web-fragment.xml and jar:file:///tmp/jetty-0.0.0.0-8080-hapi-fhir-jpaserver.war-_hapi-fhir-jpaserver-any-960398556907507961.dir/webapp/WEB-INF/lib/spring-web-5.1.6.RELEASE.jar!/META-INF/web-fragment.xml
	at org.eclipse.jetty.webapp.MetaData.addFragment(MetaData.java:285)
	at org.eclipse.jetty.webapp.FragmentConfiguration.addWebFragments(FragmentConfiguration.java:88)
	at org.eclipse.jetty.webapp.FragmentConfiguration.preConfigure(FragmentConfiguration.java:39)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:192)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:502)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:172)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:430)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:65)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:145)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:576)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:238)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
2019-07-29 17:26:01.393:INFO:oejs.AbstractConnector:main: Started ServerConnector@27808f31{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-07-29 17:26:01.394:INFO:oejs.Server:main: Started @2910ms

**Comment by seanmcilvenna** [comment]
A quick google search shows the following:
https://stackoverflow.com/questions/5802096/duplicate-fragment-name-error-jetty-maven-plugin

They suggest adding `<allowDuplicateFragmentNames>true</allowDuplicateFragmentNames>` to the web.xml file.

Please consider forking the repo, applying this change, and seeing if it solves the problem...

**Comment by Jammjammjamm** [comment]
I think that is actually a reference to `pom.xml`, which already contains that tag: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/pom.xml#L232

**Comment by seanmcilvenna** [comment]
I'm no jetty/maven expert... but, it seems that it's pointing specifically to "spring-web". Maybe consider adding that `<allowDuplicateFragmentNames>` to the `<dependency>` for spring_web? A long shot, though.

I also found this: http://forum.broadleafcommerce.org/viewtopic.php?t=2145
Suggesting that `metadata-complete="true"` be added to the web.xml file. Currently it is set to "false".

**Comment by Jammjammjamm** [comment]
That did get me past the error, but then caused a bunch of more errors. I ran `mvn clean`, rebuilt the image, and now it works, so who knows what caused the problem.

**Comment by jamesagnew** [comment]
@Jammjammjamm is the fix something you'd be willing to file a PR for?

**Comment by Jammjammjamm** [comment]
I don't think there's anything to fix. I asked a coworker of mine to try running it, and they didn't have any problems, indicating that it was a problem with my local machine. At that point I decided to try a clean build, so I ran `mvn clean` and then everything worked.

**Comment by jamesagnew** [comment]
Hah, that's annoying. :)

Ah well, thanks for letting me know.

**Comment by seanmcilvenna** [comment]
good to know. thanks!
