### ISSUE TITLE
Error when running Docker with PostgreSQL

### ISSUE THREAD

**Issue by neumartin** [hapifhir/hapi-fhir-jpaserver-starter#573]
Hi!

I have this docker-compose.yml

```
version: '3.7'
services:
  web:
    image: "hapiproject/hapi:latest"
    ports:
      - "8090:8080"
    volumes:
      - /home/martin/docker/hapi-fhir/config/application.yaml:/data/hapi/application.yaml
    environment:
      SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yaml'
```

And this application.yaml

```
spring:
  datasource:
    url: 'jdbc:postgresql://172.17.0.3:5432/hapi'
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
```

But when starts, I get this error:

```
hapi-fhir-web-1  | 
hapi-fhir-web-1  |   .   ____          _            __ _ _
hapi-fhir-web-1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
hapi-fhir-web-1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
hapi-fhir-web-1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
hapi-fhir-web-1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
hapi-fhir-web-1  |  =========|_|==============|___/=/_/_/_/
hapi-fhir-web-1  | 
hapi-fhir-web-1  |  :: Spring Boot ::               (v2.7.11)
hapi-fhir-web-1  | 
hapi-fhir-web-1  | 
hapi-fhir-web-1  | 2023-08-02 01:01:14.344 [main] INFO  ca.uhn.fhir.jpa.starter.Application [StartupInfoLogger.java:55] Starting Application using Java 17.0.6 on f9256a81aeb1 with PID 1 (/app/main.war started by nonroot in /app)
hapi-fhir-web-1  | 2023-08-02 01:01:14.346 [background-preinit] INFO  o.h.validator.internal.util.Version [Version.java:21] HV000001: Hibernate Validator 6.1.5.Final
hapi-fhir-web-1  | 2023-08-02 01:01:14.348 [main] INFO  ca.uhn.fhir.jpa.starter.Application [SpringApplication.java:631] No active profile set, falling back to 1 default profile: "default"
hapi-fhir-web-1  | 2023-08-02 01:01:14.549 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext [AbstractApplicationContext.java:591] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/app/main.war!/WEB-INF/classes!/ca/uhn/fhir/jpa/starter/common/FhirServerConfigDstu2.class]; nested exception is java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because the return value of "org.springframework.core.env.Environment.getProperty(String)" is null
hapi-fhir-web-1  | 2023-08-02 01:01:14.866 [main] ERROR o.s.boot.SpringApplication [SpringApplication.java:821] Application run failed
hapi-fhir-web-1  | org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/app/main.war!/WEB-INF/classes!/ca/uhn/fhir/jpa/starter/common/FhirServerConfigDstu2.class]; nested exception is java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because the return value of "org.springframework.core.env.Environment.getProperty(String)" is null
hapi-fhir-web-1  |      at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:457)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:316)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:276)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:128)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:295)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:206)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:174)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
hapi-fhir-web-1  |      at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
hapi-fhir-web-1  |      at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
hapi-fhir-web-1  |      at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:748)
hapi-fhir-web-1  |      at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
hapi-fhir-web-1  |      at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
hapi-fhir-web-1  |      at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
hapi-fhir-web-1  |      at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
hapi-fhir-web-1  |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
hapi-fhir-web-1  |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
hapi-fhir-web-1  |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
hapi-fhir-web-1  |      at ca.uhn.fhir.jpa.starter.Application.main(Application.java:44)
hapi-fhir-web-1  |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
hapi-fhir-web-1  |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
hapi-fhir-web-1  |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
hapi-fhir-web-1  |      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
hapi-fhir-web-1  |      at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
hapi-fhir-web-1  |      at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
hapi-fhir-web-1  |      at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
hapi-fhir-web-1  |      at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
hapi-fhir-web-1  | Caused by: java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because the return value of "org.springframework.core.env.Environment.getProperty(String)" is null
hapi-fhir-web-1  |      at ca.uhn.fhir.jpa.starter.annotations.OnDSTU2Condition.matches(OnDSTU2Condition.java:14)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:88)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:71)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isConditionMatch(ClassPathScanningCandidateComponentProvider.java:512)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isCandidateComponent(ClassPathScanningCandidateComponentProvider.java:495)
hapi-fhir-web-1  |      at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:430)
hapi-fhir-web-1  |      ... 28 common frames omitted
hapi-fhir-web-1 exited with code 1
```

**Comment by jkiddo** [comment]
your application.yaml does not state what FHIR version should be used.

**Comment by jkiddo** [comment]
@neumartin did it fix your problem to state the FHIR version?

**Comment by westernsalt** [comment]
How could you fix that problem? I need your help :(;

**Comment by neumartin** [comment]
> How could you fix that problem? I need your help :(;

Use the complete configuration file, like this: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/573#issuecomment-1674742469
