### ISSUE TITLE
 spring-security-core error

### ISSUE THREAD

**Issue by netlogo-it** [hapifhir/hapi-fhir-jpaserver-starter#670]
The hapi-fhir-storage-cr library imports the spring security library in version 5.7.8 incompatible with spring boot 3.2.0.
In fact, if I import spring-boot-starter-security to implement authentication with OAuth2 it conflicts with the right spring-security-core 6.2.0 library.
No errors occur during compilation but when the application is executed the following error occurs:

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.config.annotation.web.builders.HttpSecurity]: Factory method 'httpSecurity' threw exception with message: org/springframework/security/core/context/DeferredSecurityContext
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:647)
        ... 31 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/security/core/context/DeferredSecurityContext
        at org.springframework.security.config.annotation.web.configurers.SessionManagementConfigurer.<init>(SessionManagementConfigurer.java:150)
        at org.springframework.security.config.annotation.web.builders.HttpSecurity.sessionManagement(HttpSecurity.java:582)
        at org.springframework.security.config.annotation.web.configuration.HttpSecurityConfiguration.httpSecurity(HttpSecurityConfiguration.java:120)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140)
        ... 32 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.security.core.context.DeferredSecurityContext
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 40 common frames omitted

For now the problem has been overcome with the following explicit declaration in the pom.xml file:

        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-storage-cr</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.security</groupId>
                    <artifactId>spring-security-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

but I don't know if this affects other parts of the code.

**Comment by XcrigX** [comment]
see https://github.com/hapifhir/hapi-fhir/issues/5793

I worked around the issue with the same exclusion specified. So far I have not found any problems, but I am not using the CQL features which I think hapi-fhir-storage-cr is related to.

**Comment by jkiddo** [comment]
Closing here as it should be resolved in https://github.com/hapifhir/hapi-fhir
