### ISSUE TITLE
Invalid attribute value "4.0.1": Unknown FHIRVersion code '4.0.1'

### ISSUE THREAD

**Issue by jeffeastman** [hapifhir/hapi-fhir-jpaserver-starter#96]
I'm trying to load the first LINK_NEXT page returned by a query with the following code from a v4.2.0 HAPI-FHIR server using hapi-fhir-client-4.2.0.jar and I'm getting this exception which seems wrong, since the server reports it's FHIR version is "4.0.1" in it's metadata. It worked with v4.0.0 and I've been writing resources to this server for weeks. I just cannot read them all back. 

Any help would be appreciated.
```
	public List<IBaseResource> getEntries(IBaseBundle baseBundle, IGenericClient client) {
		List<IBaseResource> list = new ArrayList<>();
		Bundle bundle = (Bundle) baseBundle;
		for (BundleEntryComponent comp : bundle.getEntry()) {
			IBaseResource m = comp.getResource();
			list.add(m);
		}
		while (bundle.getLink(Bundle.LINK_NEXT) != null) {
			bundle = client.loadPage().next(bundle).execute();
			for (BundleEntryComponent comp : bundle.getEntry()) {
				IBaseResource m = comp.getResource();
				list.add(m);
			}
		}
		return list;
	}
```
```
Exception in thread "main" ca.uhn.fhir.rest.client.exceptions.FhirClientConnectionException: Failed to retrieve the server metadata statement during client initialization. URL used was http://localhost:8380/hapi-fhir-jpaserver/fhir/metadata
	at ca.uhn.fhir.rest.client.impl.RestfulClientFactory.validateServerBase(RestfulClientFactory.java:312)
	at ca.uhn.fhir.rest.client.impl.RestfulClientFactory.validateServerBaseIfConfiguredToDoSo(RestfulClientFactory.java:264)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:227)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:434)
	at ca.uhn.fhir.rest.client.impl.GenericClient$GetPageInternal.execute(GenericClient.java:734)
	at org.mihin.patientgen.export.FhirR4Converter.getEntries(FhirR4Converter.java:484)
	at org.mihin.patientgen.servers.FhirServer.getAllResources(FhirServer.java:460)
	at org.mihin.patientgen.RingPatcher.main(RingPatcher.java:26)
Caused by: ca.uhn.fhir.rest.client.exceptions.FhirClientConnectionException: Failed to parse response from server when performing GET to URL http://localhost:8380/hapi-fhir-jpaserver/fhir/metadata - ca.uhn.fhir.parser.DataFormatException: Invalid attribute value "4.0.1": Unknown FHIRVersion code '4.0.1'
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:392)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:434)
	at ca.uhn.fhir.rest.client.impl.GenericClient$FetchConformanceInternal.execute(GenericClient.java:701)
	at ca.uhn.fhir.rest.client.impl.RestfulClientFactory.validateServerBase(RestfulClientFactory.java:305)
	... 7 more
Caused by: ca.uhn.fhir.parser.DataFormatException: Invalid attribute value "4.0.1": Unknown FHIRVersion code '4.0.1'
	at ca.uhn.fhir.parser.StrictErrorHandler.invalidValue(StrictErrorHandler.java:49)
	at ca.uhn.fhir.parser.LenientErrorHandler.invalidValue(LenientErrorHandler.java:90)
	at ca.uhn.fhir.parser.ParserState$PrimitiveState.attributeValue(ParserState.java:1286)
	at ca.uhn.fhir.parser.ParserState.attributeValue(ParserState.java:85)
	at ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:1110)
	at ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:1015)
	at ca.uhn.fhir.parser.JsonParser.doParseResource(JsonParser.java:196)
	at ca.uhn.fhir.parser.JsonParser.doParseResource(JsonParser.java:178)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:710)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:695)
	at ca.uhn.fhir.rest.client.impl.BaseClient$ResourceResponseHandler.invokeClient(BaseClient.java:580)
	at ca.uhn.fhir.rest.client.impl.BaseClient$ResourceResponseHandler.invokeClient(BaseClient.java:532)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:382)
	... 10 more

```

**Comment by jeffeastman** [comment]
Digging in with the debugger, it's blowing up in Enumeration here
<img width="483" alt="Screen Shot 2020-05-05 at 10 15 25 AM" src="https://user-images.githubusercontent.com/8631956/81076546-c301f200-8eb9-11ea-9ded-f07180fb1cdf.png"> trying to do this 
<img width="761" alt="Screen Shot 2020-05-05 at 10 16 22 AM" src="https://user-images.githubusercontent.com/8631956/81076605-d2813b00-8eb9-11ea-8547-ec7711d5db20.png">

**Comment by jeffeastman** [comment]
Meh, this is some jar file version snafu of my own creation. Closing
